// Pool Legends — Rock Oracle
// Each legend follows The Deep Record style guide: content/deep-record.md
//
// Required per legend:
//   1. Country — Aboriginal nation name
//   2. Date or era — construction year/decade or geological age
//   3. Geology — rock formation name
//
// Legends are keyed by pool ID from src/pools.js.
// Legends pending research are marked with TODO.

export const LEGENDS = {

  // ── QUEENSLAND ──────────────────────────────────────────────────────────────

  'strand-rockpool': `The Strand Rockpool is a long-running Townsville foreshore swim site, now entering another council-led redevelopment phase focused on safety, resilience, and filtration upgrades. Townsville City Council has publicly scoped the revamp and invited community input. This coast is on the Country of the Bindal and Wulgurukaba peoples, acknowledged by Council as Traditional Landowners of the Townsville region. Mara has seen this pool in multiple forms. Councils redraw the edges. She keeps filling what remains open to the tide.`,

  'yeppoon-lagoon': `Yeppoon Lagoon is a modern council-managed lagoon precinct rather than a traditional hewn ocean bath. Recent Livingstone Shire Council notices document staged maintenance works, temporary closures, and remediation of finish defects. The precinct is on Country acknowledged by Council under Darumbal, Woppaburra, and Barada Kabalbara Yetimarala custodianship. Mara arrives differently at engineered pools: less as force, more as weather and salt in the air. The structure is new; the coast is not.`,

  'noosa-fairy-pools': `The Fairy Pools at Noosa Heads are a natural coastal formation within Noosa National Park, documented in local archives for decades. Noosa Council records and historical imagery show the site has been part of the region's coastal memory since at least the mid twentieth century. Access and use are managed through park controls rather than municipal pool operations. Mara did not wait for walls here. She left hollows in rock and moved on. People kept returning to the same two pockets of water.`,

  'kings-beach-pool': `Kings Beach Ocean Pool is the Sir Francis Nicklin Memorial Pool, listed by Sunshine Coast Council as a 25-metre ocean pool with public amenities on the Caloundra foreshore. Council notices also record major refurbishment closures, part of the ongoing lifecycle of a heavily used civic pool. The Sunshine Coast sits across Kabi Kabi and Jinibara Country, acknowledged by Council. Mara tolerates repairs. A pool that stays open for decades is always partly original and partly replacement.`,

  'snapper-rocks-pool': `At Snapper Rocks, the pool story is mostly historical: Gold Coast archives record Jack Evans sea baths at the site, while current council listings focus on Apex Park and surf access rather than an active municipal ocean pool. The old baths remain in local memory at the NSW-QLD edge of the headland. Mara turned here in the current. The map calls it a border; the water does not.`,

  // ── NEW SOUTH WALES — NORTH COAST ────────────────────────────────────────

  'angourie-blue-pool': `Clarence Valley Council identifies Angourie's Blue and Green Pools as former quarry works linked to stone for the original Yamba rockwall. Council also notes the reserve's cultural significance to the Yaegl community. NSW Government safety guidance describes the Blue Pool as extremely deep and occasionally closed during algae events. Mara did not set out to make a monument here. Industry cut the void first; water kept it.`,

  'sawtell-pool': `Sawtell Memorial Rock Pool appears in Coffs local archive records from around the 1960s at Bonville Headland. City of Coffs Harbour continues to run seasonal reopening cycles for the pool, with published dates and holiday exceptions. The pool has stayed in active civic use across generations rather than becoming a static memorial object. Mara respects that pattern: grief held in a place people keep entering.`,

  'forster-fairy-pool': `The Forster Fairy Pool is a natural rock pool near the Booti Booti coast, in a headland system where surf, tide, and access conditions change quickly. Official records name the broader national park setting more clearly than the pool's early chronology. The place remains known in local use even where archival detail is light. Mara leaves some places lightly named. Not every pool arrives with paperwork.`,

  'forster-ocean-baths': `MidCoast Council records the official opening of Forster Ocean Baths, known locally as the Bull Ring, on 18 January 1936. Council also publishes the bath dimensions and maintenance cycle: regular closure, drain-down, pressure clean, sand replacement, and refill from the ocean. The pool remains unsupervised by lifeguards, so operations rely on signage and local judgement. Mara likes this one for its persistence: old walls, routine upkeep, no theatre.`,

  // ── NEW SOUTH WALES — NEWCASTLE ──────────────────────────────────────────

  'bogey-hole': `The Bogey Hole at Newcastle is probably the oldest ocean bath in Australia. It was cut from the rock platform at King Edward Park around 1820 — possibly earlier — on the orders of Lieutenant-Colonel James Morisset, commandant of the Newcastle penal settlement. Convict labour made the cuts. The word "bogey" comes from the Dharug language, meaning to bathe. The rock is Newcastle Coal Measures — sandstone and shale, Permian in age, roughly 250 million years old. This is Awabakal Country. The men who carved it were transported here from the cold. The pool they made is still here. Mara fills it every tide, without comment.`,

  'newcastle-ocean-baths': `City of Newcastle marks 25 November 1922 as the official opening date of Newcastle Ocean Baths, with swimming use at the site predating that ceremony. After a major restoration project, the complex reopened in December 2023, and Council now operates it year-round with scheduled cleaning windows. The baths were also entered on the NSW State Heritage Register in 2025. Mara has watched this pool move from civic optimism to conservation work and back to daily use.`,

  'bar-beach-pool': `City of Newcastle describes the Bar Beach pool as a natural rock pool in the beach's northern corner, long used as a family swimming spot. It is less a constructed bath than a protected indentation adopted by swimmers over time. Council's beach operations treat it as part of the broader patrol and safety setting at Bar Beach. Mara did not need to be precise here. The coast already had a shape people could trust.`,

  'merewether-baths': `Merewether Ocean Baths opened in 1935 and are presented by City of Newcastle as a flagship ocean-bath facility, open year-round subject to maintenance closures. Council publishes regular cleaning schedules and patrol periods, reflecting how heavily the baths are used across seasons. In scale and continuity, Merewether functions as civic infrastructure, not a novelty. Mara approves of long commitment: one pool, repeatedly maintained, never treated as temporary.`,

  // ── NEW SOUTH WALES — NORTHERN BEACHES ──────────────────────────────────

  'palm-beach-pool': `Warringah Shire Council built the first pool here in 1923 — sixteen by sixteen metres, cut into the Hawkesbury Sandstone at the southern end of the beach. The larger 50-metre pool followed in 1935. In 1946 the Palm Beach Amateur Swimming Club was founded, sponsored by the surf lifesaving club, and a young physiology lecturer from the University of Sydney named Forbes Carlile began coaching there. His work at this pool led directly to his appointment as Australian swimming coach for the 1948 London Olympics. Jack Carter — known as "Johnny" — taught children to swim here from 1948 until late in life. In 2019 the pool was officially renamed the Jack 'Johnny' Carter Pool. This is Garigal Country, Guringai language group. The sandstone is roughly 240 million years old, laid down when this coast was a river delta. Mara pressed into it first.`,

  'bilgola-pool': `Council minutes from 1 March 1961 record a petition from local citizens and the Bilgola Surf Club requesting a pool on the rock shelf at the southern end of the beach. The pool was built shortly afterward — 50 metres by 15 metres, with an adjacent wading pool separated by post-and-chain fencing. A wave deflector in the north wall draws water through a scupper to maintain the level. In 1968 the council blasted the adjacent cliff to remove loose rocks; some fell into the pool. The cliff was smaller after that. This is Garigal Country, Guringai language group. The rock is Hawkesbury Sandstone, 240 million years old. Mara noticed the steep geometry of this cove — the way the headlands hold the water between them. She pressed into the southern shelf. The residents made it into something.`,

  'avalon-pool': `Warringah Council built the first pool here in 1917 with community funds and the assistance of a local developer named A.J. Small. It was lengthened in 1922 — a ladies' dressing shed added — enlarged and deepened again in 1937, with a children's pool added in 1939. In 1998, several episodes of *Baywatch* were filmed at the pool. A proposal to make Avalon the permanent *Baywatch* filming location was defeated by local opposition; Pittwater Council permanently banned future productions after the crew detonated a yacht offshore without warning, injuring a woman in her eighties. This is Garigal Country, Guringai language group. The sandstone is Hawkesbury formation, 240 million years old. Mara rested here. She has no view on the television.`,

  'newport-pool': `Three earlier pools at this site failed to hold together. In 1925 Warringah Council built the present pool — 37 feet in length, total cost £560, of which the council contributed £310. It was officially opened at a carnival, reported in the *Sydney Morning Herald* of 1 February 1926. Newport was the seventh ocean pool built in Warringah Shire, following Harbord, Dee Why, Collaroy, Mona Vale, Avalon, and Palm Beach — a sequence that reads now like the order of a swim. This is Garigal Country, Guringai language group. The sandstone is Hawkesbury formation. Mara moved quickly through Newport. The headland geometry made her uncomfortable. The pool is the mark of her passing, not her resting.`,

  'mona-vale-pool': `Warringah Shire Council first opened baths at Mona Vale in 1914. The Depression-era reconstruction of the 1930s — unemployed labour paid through the relief scheme — carved the pool deeper from the natural rock shelf, added electric lights, and shaped the 30-metre main pool and adjacent children's basin that still exist. During the Second World War, troops camped on the headland used the baths in large numbers. This is Gai-mariagal Country, Guringai language group. The sandstone is Hawkesbury formation, roughly 240 million years old. Mara pressed into this platform in a period beyond memory. The Depression workers pressed in again. The pool holds both.`,

  'north-narrabeen-pool': `Councillors Atkins and Parr requested a feasibility estimate for a pool here in January 1927. The council took its time. Tenders were sought in September 1933; contractor John Macdonald's bid of £494 was accepted in October. The pool — 50 metres, built under the Unemployment Relief Scheme — opened on 3 March 1935, officially opened by Warringah Shire President Councillor Austen. Gai-mariagal descendant Dennis Foley has described Narrabeen Lagoon as "the heart of our world" — the lagoon to the west was a secular living area; the plateau above Collaroy was used for ceremony and education. This is Gai-mariagal Country, Guringai language group. The sandstone is Hawkesbury formation. Mara arrived at this headland from the north with momentum. The pool is where she slowed.`,

  'dee-why-pool': `In 1915 members of the Dee Why Surf Life Saving Club carved a 20-foot square pool from the rock shelf at the southern end of the beach — volunteer labour, community tools. The enlarged pool was officially opened in 1919 at a final cost of £192. A children's pool followed in October 1930. In 1922 the Dee Why Ladies Amateur Swimming Club was formed, one of the oldest ladies' swimming clubs in New South Wales. The name Dee Why likely derives from a Guringai word for the freshwater lagoon behind the beach. This is Cannalgal Country, Guringai language group. The rock is Hawkesbury Sandstone. Mara pressed into this headland and felt the pull of the lagoon behind it — fresh water calling to salt. She spent longer here than the stone records.`,

  'north-curl-curl-pool': `A natural pool existed here before anyone improved it — a hollow worn by wave action in the platform at the base of Dee Why Head. In 1937, under the Unemployment Relief Scheme, workers deepened and walled it: 90 feet by 165 feet, cost £400. Heavy seas destroyed the pool in 1947. It was rebuilt and reopened in 1957, smaller than before. Since 1962 a group called the Cool Cats Swimming Club has met here regularly. This is Cannalgal Country, Guringai language group. The rock is Hawkesbury Sandstone, 240 million years old. Mara made the original hollow. The 1937 workers made it larger. The sea made it smaller again. The Cool Cats stayed.`,

  'south-curl-curl-pool': `The South Curl Curl Improvement Association petitioned Warringah Council in 1924 after community discussions the previous year. The pool was built and opened in 1926 — 53 metres by 36 metres. A central dividing wall was added in 1937, splitting the pool into lap and children's sections. In 1986 the council renamed it the Howard Hansen Memorial Pool, honouring a South Curl Curl surf lifesaving club member who had taught generations of local children to swim. Hansen died on 19 December 1985, aged 70. This is Cannalgal Country, Guringai language group. The sandstone is Hawkesbury formation. Mara pressed into this headland twice — once going south past the northern pool, once again at the southern cut. She found the repetition appropriate. The rock could hold two memories.`,

  'collaroy-pool': `Contractor Arthur Larkin built the original pool for Warringah Shire Council in 1926. It was extended and deepened to a full 50-metre eight-lane lap pool in 1937, a toddlers' wading pool added at the same time. The shape is unusual: the pool follows the natural curve of the rock platform rather than imposing a rectangle on it, with the natural sandstone lines on the shore side and a straight concrete wall on the ocean side. The 2016 storms removed metres of dune from the houses behind the beach. The pool, cut into the platform itself, was unmoved. This is Gai-mariagal Country, Guringai language group. The sandstone is Hawkesbury formation. Mara chose the stone side. So did Larkin.`,

  'freshwater-pool': `The Harbord Beach Improvement Committee lobbied for years; the Freshwater Surf Club raised money through concerts and carnivals. Contractor W.H. Morgan built it for £472. It opened on 28 November 1925 — officially the first ocean pool on Sydney's Northern Beaches. Extended to 50 metres in 1962. On the afternoon of 24 December 1914 — eleven years before the pool was built — Hawaiian Olympic champion Duke Kahanamoku had shaped a surfboard from local sugar pine and gave the first surfboard demonstration in Australia on this beach. A second demonstration on 10 January 1915 involved a fifteen-year-old local girl, Isabel Letham, who rode the board with him. A bronze statue of Kahanamoku, donated by the Harbord Diggers Club, was installed in McKillop Park in 1986. This is Gayamaygal Country, Guringai language group. Mara recognised Kahanamoku when he entered the water. He was moving through it the way she moves. She has no other explanation for him.`,

  'queenscliff-pool': `Unemployment Relief Scheme funds paid for this pool in 1937 — the same Depression-era programme that built North Narrabeen, North Curl Curl, and Mona Vale in the same decade. The walls are 50 metres, though they are not parallel: the pool follows the rock face rather than a surveyor's line. It was heritage-listed, and in 2014 was resurfaced and renovated — wider ramp access, safer stairs, new ladders — while its original shape and position were retained. The Queenscliff Surf Lifesaving Club has operated from this headland since 1907, thirty years before the pool was built. This is Gayamaygal Country, Guringai language group. The headland divides two beaches with different characters. Mara came around this point and felt the change. The pool is at the hinge.`,

  'fairy-bower-pool': `Local residents built this pool in 1929 without council direction — community labour, shark safety the stated reason. Fishermen landing catches at Shelly Beach had brought sharks to the bay; the enclosed pool was the answer. The pool is triangular, about 20 metres from end to end, ankle-deep at the eastern end and 1.5 metres at the western wall. In 1997 artist Helen Leete installed ceramic "Sea Nymphs" — The Oceanides — on the seaward ledge, as part of a Manly Council public sculpture programme. A storm in 2016 destroyed the originals. Locals raised $57,000 to remake them in bronze; the new Oceanides were reinstalled about fifteen months later. This is Gayamaygal Country — the name Kai'ymay (Manly Cove) plus the suffix -gal gives this clan its name. The rock is Hawkesbury Sandstone. Mara rested here. The alcove suggested it. She found the shelter unremarkable and stayed anyway.`,

  // ── NEW SOUTH WALES — SYDNEY HARBOUR ─────────────────────────────────────

  'balmoral-baths': `Mosman Council opened baths here in 1897 on a beach the Cammeraygal had used as a burial ground. When the promenade was later constructed, workers uncovered at least seven skeletal remains interred in ceremonial fashion. A shell midden at the beach's southern end contains pumice traced to the Tonga-Kermadec volcanic arc — evidence the Cammeraygal were participating in Pacific maritime exchange networks thousands of years before settlement. A steel shark net arrived in 1935 after fatal attacks in Middle Harbour. It was made permanent in 1958 and controversially removed in 2008. Mara does not come into the harbour. She sends the tidal current as her representative. The burial ground predates the net, the baths, and the name.`,

  'maccallum-pool': `Fred Lane won Australia's first Olympic gold medals at the 1900 Paris Games — including the 200m obstacle race, which required swimming over and under a series of moored boats. Decades later, retired at Cremorne Point, he began stacking harbour boulders into the shape of a tidal pool. His neighbour Hugh MacCallum took over, raised £600 from local residents, and finished the work. A plaque was unveiled on 29 April 1933. The pool is 33 metres. Entry remains free. This is Cammeraygal Country — the Cammeraygal called this place Wulworra-Jeung. Nearby Kurraba Point was quarried for 8,000 tonnes of sandstone in the 1860s to build Fort Denison. The pool is what was left after the quarrying. Lane built in it. Mara filled it.`,

  'murray-rose-pool': `A man named Gurrah held the fishing rights to this beach. In the colonial period he sold them to the landowner William Busby for seven shillings. The beach carried Busby's name for decades, then the estate's name — Redleaf — and in 1941 Woollahra Council built a formal shark-proof enclosure here. Murray Rose learned to swim in this pool as a child. In 1956 at the Melbourne Olympics, aged seventeen, he won three gold medals in a single Games — the youngest swimmer ever to do so. He died in April 2012 and the pool was renamed that July. This is Gadigal Country. Gurrah's seven shillings bought something that would outlast everything either of them knew.`,

  'dawn-fraser-baths': `Built in 1882 on the Wangal Country harbour foreshore — then called White Horse Baths, for the point named after a bushranger's escape. Frederick Ward, "Captain Thunderbolt," swam from Cockatoo Island gaol in 1863 and was met here by his companion Mary Ann Bugg with a white horse. The baths were legal when the beaches were not: the 1838 NSW Police Act banned ocean bathing during daylight hours, and enclosed harbour baths were the lawful exception. The Balmain Swimming Club was founded here in 1884 — the first swimming association in Australia. In 1964 the baths were renamed for Dawn Fraser, who won the 100m freestyle at three consecutive Olympics. She grew up in Balmain. She learned to swim here.`,

  // ── NEW SOUTH WALES — EASTERN SUBURBS ───────────────────────────────────

  'bondi-icebergs': `The name Bondi comes from a Dharawal word for water breaking over rocks. A storm in 1899 uncovered vast quantities of stone tools in the dunes — evidence of the Bidjigal, Birrabirragal, and Gadigal peoples who knew this beach long before the pool. The first baths here were built in 1887 by NSW government engineers; the current 50-metre pool opened in 1931, enlarged in 1932. The Icebergs Club was founded in 1929 by surf lifesavers who refused to stop training over winter. Their rule: swim three out of four Sundays for five consecutive years, or you don't belong. Women were admitted as full members — not "Mermaids," as they had been classified — in 1995. Mara kept going.`,

  'bronte-baths': `Council records show £150 was allocated in 1883; engineer A. Williams — the same engineer who designed the Bondi baths — completed the work and the pool opened on 6 February 1888. Bathing hours were strictly gendered in the early decades, men and women assigned separate times. The word "bogey" — which locals used for the Bronte baths, as for the Newcastle Bogey Hole — comes from a Dharug word meaning to bathe: the same language that named country all along this coast. This is Gadigal Country. The rock is Hawkesbury Sandstone, 230 million years old. Mara pressed into this headland in 1883. Williams followed her marks.`,

  'clovelly-pool': `Swimming happened here from 1895, when the inlet was already known — a narrow arm of the sea reaching into the Hawkesbury Sandstone cliffs, calm enough for children. During the Depression, it was formalised as a relief project, unemployed men paid to shape the existing inlet with concrete. A storm in 1938 destroyed that structure. The current pool was designed in 1962 by local resident Geoff James, who drew his plans by hand. It was eventually renamed the Geoff James Pool. This is Gadigal Country. The water is still enough to see the bottom: wobbegong sharks rest on the sand, octopus live in the walls. Mara made the inlet. James improved it. The octopus arrived on their own terms and answered to neither.`,

  'giles-baths': `The baths now known as Giles were first called Lloyd's Baths. In 1924 Oscar Giles took over the lease for £268 per year and spent the next four years building — the work was completed between 1925 and 1928. Giles installed electric treatment chairs and sweat boxes, popular health interventions of the era. The structures were demolished in 2000; only the original portico and the Inglis sundial remain. This is Gadigal Country. The rock is Hawkesbury Sandstone. Five ocean pools share this headland — the densest concentration in Australia, all carved from the same shelf, all fed by the same tides. Mara filled Lloyd's baths, Giles' baths, and whatever comes next. She does not keep track of the names.`,

  'ross-jones-pool': `The Ross Jones Memorial Pool was built in 1947, funded in part from £963 of post-war reparations money — what peace could buy, at that price, in a place that wanted to build something. Roscoe Samuel Jones was a Randwick councillor and surf lifesaving club president; the pool named for him sits on the Coogee headland among four others, all cut from the same Hawkesbury Sandstone shelf, all fed by the same tides. This is Gadigal Country. The headland has been a gathering place far longer than the pools. Jones is the only one of the five whose story begins with what was left over from a war.`,

  'mcivers-baths': `The Coogee Ladies' Baths have been women-only since before they were formally established. The headland site was a women's place before colonial settlement — used for bathing, fishing, and birthing by Gadigal women, a sacred designation not erased so much as continued in a different form. Colonists first visited in the 1830s; the baths were formally recorded from 1876. In 1912 at the Stockholm Olympics, Fanny Durack won gold in the 100m freestyle and Mina Wylie won silver — the first time women competed in Olympic swimming, and both had trained in Sydney ocean baths. The pool received a formal exemption from the NSW Anti-Discrimination Act in 1995, allowing the women-only policy to continue. It remains the last women-only seawater baths in the world. This is Gadigal Country. Mara fills it the same way she fills everything. She has no opinion on the exemption.`,

  'wylies-baths': `Henry Wylie leased the Coogee headland in 1902 and opened the baths on 12 December 1907 — the first mixed-gender ocean pool in Australia, a distinction worth noting in an era of strictly separated bathing. The pool is 50 yards. His daughter Mina trained here daily, swimming half a mile before breakfast. Between 1906 and 1934 she won 115 titles. At the 1912 Stockholm Olympics she won silver in the 100m freestyle — the same race Fanny Durack won gold. In 2003 the pool was listed on the NSW State Heritage Register. This is Gadigal Country. The sandstone is Hawkesbury formation, 230 million years old. Mara has been filling these baths since the first season. The heritage listing changed nothing about that arrangement.`,

  'mahon-pool': `Patrick Mahon was the first endorsed Labor alderman on Randwick Council. On 5 March 1935 he moved the motion to build a pool at Maroubra — then collapsed at the council table. He died on 3 September 1935, aged 43, before the pool was finished. On 3 March 1936 his family asked the council to name it the Mahon Memorial Pool. It opened around 1937. Maroubra takes its name from a Dharawal word for thunder. The sandstone is Hawkesbury formation. This is Bidjigal and Gadigal Country. At high tide the surf washes over the walls. Mara visits with force. Of all the hewn pools on this coast, this is the one she tends most actively — named for a man who died before it was done.`,

  'malabar-pool': `The pool was in use by 1895, cut into the sandstone at the northern end of Malabar Headland. In 1916 a sewer outfall was installed nearby, carrying waste from the abattoirs at Glebe Island. The pool was abandoned. In 1931 the cargo ship Malabar ran aground on the headland in a gale; thirty thousand people came to look at it over the following days. By 1985 a local school principal began petitioning for the sewer to be moved. In 1990 the Deep Water Sewer Outfall was extended offshore. The pool reopened in March 1997. The headland is now part of Malabar Headland National Park. This is Bidjigal Country. The sandstone is Hawkesbury formation. Mara had been waiting eighty years for the water to come clean. She filled it again as if no time had passed.`,

  // ── NEW SOUTH WALES — ROYAL NATIONAL PARK ────────────────────────────────

  'wattamolla-lagoon': `Wattamolla is a coastal lagoon in the Royal National Park where a waterfall drops off the sandstone headland into a sheltered basin, which connects to the sea through a sand and rock bar. The name comes from a Dharawal word meaning "place near running water." This is Dharawal Country. The sandstone headland is Hawkesbury formation, roughly 230 million years old. The lagoon is protected from the open swell and swimmable at most tides. Mara made the freshwater run over the sandstone. She made the sandstone bar between the lagoon and the sea. She was being careful. The result is a place that feels considered.`,

  'figure-eight-pools': `Mara was tired here. She pressed both palms flat against the platform to rest, fingers spread wide, and held them there while the swell moved over her. When she lifted herself back into the water, the sandstone remembered the shape of her hands. The rock is Hawkesbury formation — 230 million years old, compressed seabed, the floor of an ancient river delta. She was resting on a stone that had been ocean before she had. This is Dharawal Country. Visit within two hours of low tide, in swell under 1.7 metres. The pools close without warning. She is not always pressing down.`,

  // ── NEW SOUTH WALES — CRONULLA / ILLAWARRA ───────────────────────────────

  'cronulla-pool': `NSW Government identifies two ocean pools on the rocky platform between Cronulla and North Cronulla beaches. Sutherland Shire's local history archive records council construction of the main Cronulla pool in 1941, severe storm damage in 1987, and reconstruction completed with reopening on 26 January 1992. This is a pool defined by repair as much as origin. Mara passes this headland in rough weather and fair weather alike; the walls survive by being remade.`,

  'stanwell-park-pool': `Wollongong Council has run formal funding consultation processes for Stanwell Park Rock Pool Reserve, confirming its place as an active local asset rather than a forgotten legacy pool. Public planning attention here is mostly about upkeep and safety in a tightly constrained coastal setting. This coast sits in Dharawal Country within the Wollongong region. Mara meets this pool as a pause between escarpment and sea: narrow shelf, deliberate maintenance, continued use.`,

  'coalcliff-pool': `Coalcliff Rock Pool is listed by Wollongong Council as a public rock pool on Paterson Road, maintained within the city's coastal pool network. The clearest documented story is continuity of use and upkeep, rather than one fixed founding date. It persists through attention more than ceremony. Mara accepts incomplete archives. The pool remains.`,

  'coledale-pool': `Coledale Rock Pool appears in Wollongong Council's current rock-pool register at Northcote Street. It sits in the linked Illawarra run of pools that are still part of daily community use. The strongest record is present and practical: place, access, maintenance, return. Mara moves through this chain without ceremony.`,

  'austinmer-pool': `Austinmer Rock Pool is listed by Wollongong Council as part of the active rock-pool network on Lawrence Hargrave Drive. As with several Illawarra pools, the record is strongest on operation and continuity rather than exact origin year. The pool endures through routine stewardship and habit. Mara values places kept in use.`,

  'thirroul-pool': `Wollongong Council identifies Thirroul Pool as a saltwater facility with a 50-metre pool and toddlers' pool at Bath Street. Its present-day record is clear on configuration, access, and operation. This is infrastructure built for repetition: laps, lessons, families, return. Mara reads it the same way.`,

  'bulli-pool': `Bulli Rock Pool is listed by Wollongong Council at Farrell Road as part of the continuous coastal pool system through nearby suburbs. Here the story is less one founding date than a long operational thread: access, management, maintenance, return. On this stretch, pools are civic waypoints linked by routine use. Mara crosses them one after another.`,

  'woonona-pool': `Woonona Rock Pool is listed by Wollongong Council at Kurraba Road within the wider Illawarra chain of council-run rock pools. The strongest certainty is civic continuity: maintained, open, used. A public place does not need spectacle to matter. Mara does not distinguish between famous pools and local ones.`,

  'towradgi-pool': `Towradgi Rock Pool is council-listed and has recent public updates on sand movement and maintenance impacts. Its story is ongoing adaptation to surf and sediment rather than one founding event. This pool shifts and persists. Mara does not mistake permanence for stillness.`,

  'gentlemans-pool': `Gentlemen's Pool at North Wollongong is listed by Wollongong Council on Cliff Road. The name carries older bathing-era language, while current use sits in modern public access and council operations. Names change slower than practice. The water does not preserve old boundaries, and Mara does not either.`,

  'ladies-baths-wollongong': `Historical newspaper records and modern reporting document long-running women's bathing use on the Wollongong foreshore, including references to Ladies Baths and the Chain Baths complex. The clearest through-line is social continuity in this cove across naming changes. Mara remembers use better than titles.`,

  'continental-pool-wollongong': `Continental Pool is listed by Wollongong Council at North Wollongong as a multi-pool saltwater complex, with published dimensions and current operational updates. Council reporting also records storm impacts to pump and intake infrastructure, showing how exposed ocean-pool systems depend on constant repair. It is a pool with strong contemporary documentation and continuing civic investment. Mara stays interested where engineering keeps negotiating with swell.`,

  'nuns-pool': `ABC historical reporting and archival references identify Wollongong's Chain Baths area, often called Nun's Pool or Lovers Gully, as one of the older ocean bathing sites on this coast. The record is strongest on long public memory and place identity, not on a single uncontested formal origin date. What survives clearly is continuity: generations naming and using the same water pocket below the headland. Mara has always preferred sites with multiple names and one tide.`,

  'port-kembla-pool': `Port Kembla Pool is listed by Wollongong Council as a saltwater complex with an eight-lane 50-metre pool and toddlers' pool on Olympic Boulevard. Council documentation confirms it as one of the Illawarra's primary ocean-pool facilities in active operation today. Historical accounts of its opening are strong in regional archives, but the most robust official detail is its sustained public function. Mara likes clear purpose. This pool has kept one for a long time.`,

  'sneelocks-pool': `Sneelock's Pool is well known locally near Port Kembla, with a lighter formal archive trail than adjacent council-listed assets. It remains a recognised local site carried more by community reference than by long official documentation. Mara has left many marks that institutions recorded unevenly.`,

  'fishermens-beach-pool': `Fishermens Beach is an established Port Kembla coastal place name, while pool-specific archival detail remains limited. The enduring fact is continuity of place and use at the southern end of Wollongong's industrial coast. Mara does not require a plaque to return.`,

  // ── NEW SOUTH WALES — KIAMA & SOUTH COAST ────────────────────────────────

  'kiama-pool': `Kiama Council lists Blowhole Point Rock Pool as a current public pool with natural rock floor and variable depth. Its identity is tied to the Blowhole Point setting and open coastal conditions rather than a heavily engineered enclosure. Council status pages confirm current operation and access conditions. Mara enters here with less concern for straight lines. The rock keeps the shape it wants.`,

  'kiama-continental-pool': `Kiama Council lists Black Beach Continental Rock Pool as a 50-metre ocean pool on Shoalhaven Street, distinguishing it from the smaller Blowhole Point pool nearby. The council facility record gives clear, contemporary operational certainty even where older construction narratives vary across secondary histories. This pool is the formal lap line in Kiama's two-pool pair. Mara allows one site for drifting and one for measured distance.`,

  'gerringong-pool': `Kiama Council's current facilities identify the Gerringong area rock-pool asset at Boat Harbour, with defined access from Jupiter Street. As with several South Coast pools, contemporary council records are stronger than early construction archives in public-facing sources. The reliable claim is an active public pool embedded in the coastal path of daily use. Mara reads this as a practical pool: entered often, explained briefly.`,

  'campbells-hole': `Campbell's Hole is a known natural swimming site near Gerringong, with limited formal archival detail. The stable facts are natural formation, open-coast exposure, and ongoing local recognition. Some places are mapped socially before they are documented formally. Mara leaves room for that order.`,

  'mermaid-pool-berrara': `NSW Government location guidance places the Berrara Mermaid Pools at the southern end of Cudmirrah Nature Reserve Beach. That official reference supports the core claim: a natural pool destination tied to the reserve coastline rather than a built municipal bath. Beyond location and access context, archival detail remains limited in high-trust public sources. Mara likes these unbuilt pools best when the map says little and the water says enough.`,

  'bogey-hole-mollymook': `Mollymook's Bogey Hole is strong in local memory and regional storytelling, with fewer definitive public records than major council-listed pools. It remains a known natural rock bathing site on the Mollymook shore. Not every coastal pool arrives with formal minutes and opening ceremonies. Mara does not require either.`,

  'bermagui-blue-pool': `NSW Government lists Bermagui Blue Pool as a natural ocean rock pool and 50-metre seawater swimming hole on Pacific Drive. That listing anchors it as one of the state's clearly recognised natural pool sites, with open-coast character and strong local identity. It is less a built enclosure than a formalised natural basin in regular public use. Mara reaches it near the end of the long southward run and settles into the depth.`,

  // ── VICTORIA ────────────────────────────────────────────────────────────

  'st-kilda-sea-baths': `St Kilda Sea Baths have a well-documented multi-phase history across heritage and local-history records, including major twentieth-century rebuilds and later redevelopment. The site is part of a longer Port Phillip bathing tradition, where structures changed repeatedly while public sea-bath use persisted. Heritage and historical society records support that continuity more strongly than any single origin date. Mara does not object to reconstruction. The bay keeps receiving swimmers through each version.`,

  'middle-brighton-baths': `Middle Brighton Baths are now the focus of active Bayside Council planning and safety work, while Trove reporting confirms substantial twentieth-century sea-bath development at the site. The record shows a classic Port Phillip pattern: weather damage, rebuilding, continued social use. It is a bay bath with civic and archival visibility across eras. Mara sends the bay current here. It arrives tidally, not dramatically, and does the job.`,

  'eastern-beach-pool': `City of Greater Geelong describes Eastern Beach Reserve as an Art Deco waterfront precinct centred on a shark-proof sea bath. Archival newspaper records confirm its long role as a major civic bathing and recreation site. The pool belongs to Geelong's public bayfront identity as much as to swimmers alone. Mara sends the current into Corio Bay on schedule. The bath receives it with municipal precision.`,

  'sorrento-back-beach-pools': `Parks Victoria identifies Sorrento Back Beach as an ocean-exposed national park site where rock-pool exploration is possible at suitable tides and conditions. Official guidance emphasises hazard awareness, which is central to how these natural pools are used. This is not a managed municipal enclosure; it is contingent water in a high-energy coast setting. Mara appears here at low tide and leaves quickly when the swell turns.`,

  'cape-paterson-pool': `Cape Paterson's ocean pool is locally recognised, though high-trust archival detail in readily accessible government and heritage records remains limited. The core certainty is persistent local naming and continued coastal use. Mara allows some pools to stay partly undocumented. They are still entered, still remembered.`,

  'cairns-bay-rock-pools': `Cairns Bay rock pools are well known in local and visitor use, with lighter formal documentation than named council facilities. The stable facts are natural, tide-dependent formations and the need for careful access judgement. Mara prefers these hidden basins that stay mostly outside official registers.`,

  'lorne-sea-baths': `Lorne Sea Baths are in an active revitalisation cycle under the Great Ocean Road Coast and Parks Authority, with project conditions tied to public access and precinct operation. Current governance records make this a clearly documented contemporary coastal facility, even where older historical narratives vary by source. The present story is renewal under coastal pressure and heavy seasonal use. Mara comes to Lorne on the return line of the coast and finds a pool still being negotiated in real time.`,

};
