// Pool Legends — Rock Oracle
// Each legend follows The Deep Record style guide: content/deep-record.md
//
// Required per legend:
//   1. Country — Aboriginal nation name
//   2. Date or era — construction year/decade or geological age
//   3. Geology — rock formation name
//
// Legends are keyed by pool ID from src/pools.js.
// Legends pending research are marked with TODO.

export const LEGENDS = {

  // ── QUEENSLAND ──────────────────────────────────────────────────────────────

  'strand-rockpool': `The Strand Rock Pool opened in 1938, built by the Townsville City Council along the foreshore esplanade. Townsville sits on the unceded Country of the Wulgurukaba and Bindal peoples, who have fished and gathered on this stretch of coast for tens of thousands of years. The rock of the headlands here is not sandstone but granite — ancient, coarse, intruded from below rather than laid down from above. Mara reached this water early in her swim, when she was still moving fast and paying attention to everything. She pressed her hand into the granite and moved on. The pool was built over the mark.`,

  'yeppoon-lagoon': `The Yeppoon Lagoon was constructed in 2014 — a young pool by any measure, designed more like a public park than an ocean bath. It sits on the foreshore of Keppel Bay on the unceded Country of the Yeppoon clans of the Darumbal people. The rock beneath the lawn and concrete is ancient sedimentary formation, but the pool itself doesn't touch it — it's engineered freshwater, filled and filtered by the council, not by the sea. Mara is not here. She looked at the concrete and kept swimming. The pool is fine. It is just not hers.`,

  'noosa-fairy-pools': `The Noosa Fairy Pools are not pools anyone made. Wave action carved these two interconnected basins into the granite headland at the eastern end of Granite Bay over millions of years. The rock is coarse-grained granite, several hundred million years old, far older than the sandstone that lines the southern coast. This is Kabi Kabi Country — people of the hinterland and coast whose connection to this headland runs far deeper than the current name. Mara made these on an earlier visit, before the swim. She was testing the granite. She found it satisfying. Come within two hours of low tide. She is not always here.`,

  'kings-beach-pool': `The Kings Beach Ocean Pool at Caloundra was built in 1935 by the Caloundra Shire Council, cut into the rock shelf on the southern side of Kings Beach. This is Jinibara Country, part of the broader Kabi Kabi territory. The rock platform here is rhyolite — volcanic, dense, resistant, different from the sedimentary stone of the southern coast. Mara found it harder to press into than sandstone. The pool is proof she tried anyway. The council completed what she started.`,

  'snapper-rocks-pool': `The pool at Snapper Rocks sits at the southern tip of the Gold Coast, where the border between New South Wales and Queensland is drawn through the water. The rock shelf is volcanic — old enough to have been here when the continent wore a different shape. This is Yugambeh Country. Snapper Rocks is known as one of the most consistent surf breaks in Australia; the pool exists in its shadow, filling from the same swell. Mara turned here. The break in her swim — the southward curve of the headland — is visible in the shape of the rocks. The pool sits in the pivot point.`,

  // ── NEW SOUTH WALES — NORTH COAST ────────────────────────────────────────

  'angourie-blue-pool': `The Blue Pool at Angourie is a former bluestone quarry, worked from the 1890s until a spring broke through the floor. The quarry flooded and the flooding was permanent. The water is spring-fed and vivid — a blue with no good explanation beyond depth and clarity. An adjacent tidal lagoon fills separately at high tide. This is Yaegl Country. The rock that was quarried and the rock that remained are the same Clarence River valley stone; the difference is what Mara sent up through the floor when the quarry got too deep. She didn't intend the pool. She noticed it and stayed.`,

  'sawtell-pool': `The Sawtell Memorial Rockpool was built in 1956 as a community memorial — not to a single person but to the town's war dead, a pool as monument, a place to live rather than a place to grieve. It sits on the rock platform at the southern end of Sawtell Beach. This is Gumbaynggirr Country, whose people have known this coastline for thousands of years. The sandstone here is Coffs Harbour basin formation, younger than the Hawkesbury but carved by the same process — wave and time. Mara approved of making something alive from something lost.`,

  'forster-fairy-pool': `This pool was not made. A volcanic intrusion cooled inside the sandstone headland, and the wave action found the seam between them and worked it open over thousands of years. The result is a vivid teal pocket in the rock — backed by cliff, open to the sea, catching the light between Burgess Beach and McBrides Beach in Booti Booti National Park. This is Worimi Country. The water is cold and clear. Come at low tide; in swell it closes without warning. Mara did not make this one deliberately. She was passing close and something in the rock gave way. She has been curious about it ever since.`,

  'forster-ocean-baths': `The Forster Ocean Baths were constructed in 1930, cut from the rock platform at the southern end of Forster Beach by the Great Lakes Council. Forster sits on the unceded Country of the Worimi people, who have occupied this coast for at least forty thousand years. The sandstone here is part of the Myall Lakes basin formation, laid down in shallow coastal waters during the Permian period. The baths face north-east and are sheltered somewhat by the headland; on calm days the water barely moves. Mara passed here going south. The baths were cut into her wake.`,

  // ── NEW SOUTH WALES — NEWCASTLE ──────────────────────────────────────────

  'bogey-hole': `The Bogey Hole at Newcastle is probably the oldest ocean bath in Australia. It was cut from the rock platform at King Edward Park around 1820 — possibly earlier — on the orders of Lieutenant-Colonel James Morisset, commandant of the Newcastle penal settlement. Convict labour made the cuts. The word "bogey" comes from the Dharug language, meaning to bathe. The rock is Newcastle Coal Measures — sandstone and shale, Permian in age, roughly 250 million years old. This is Awabakal Country. The men who carved it were transported here from the cold. The pool they made is still here. Mara fills it every tide, without comment.`,

  'newcastle-ocean-baths': `The Newcastle Ocean Baths opened in 1922, built on the rock platform at Nobbys Beach by the Newcastle City Council — a public facility for a city of steel workers, miners, and dockworkers who had earned the right to swim. This is Awabakal Country. The rock is Newcastle Coal Measures, the same Permian sandstone and shale that underlies the Bogey Hole to the south. Mara had already been here for a century by the time the public baths opened. The Bogey Hole was her first experience of being carved into. The civic baths were the second. She has grown accustomed to it.`,

  'bar-beach-pool': `The Bar Beach Rock Pool sits on the platform between Bar Beach and Merewether, carved into the Newcastle Coal Measures — Permian sedimentary rock, roughly 250 million years old, dense with the compressed remnants of a coal-age swamp. This is Awabakal Country. Bar Beach has been a swimming destination since the late nineteenth century; the pool formalised what the rock platform had always offered. Mara came through here moving south, after Newcastle. She felt the coal in the stone — something different from the river sandstone further south. She pressed into it with more force than usual, curious about what was buried inside.`,

  'merewether-baths': `The Merewether Ocean Baths opened in 1935, among the largest ocean baths in the Southern Hemisphere — a tidal enclosure two hundred metres long carved into the rock platform south of Newcastle. They were built during the Depression by unemployed workers through a relief scheme: the council paid them to cut stone. The rock is Newcastle Coal Measures, Permian in age. This is Awabakal Country. Mara found the scale of what these men built — working without guaranteed wages in the middle of a depression — worth acknowledging. The pool is enormous. The circumstances that made it are part of what it is.`,

  // ── NEW SOUTH WALES — NORTHERN BEACHES ──────────────────────────────────

  'palm-beach-pool': `The Palm Beach Rockpool sits at the southern end of Palm Beach, cut into the Hawkesbury Sandstone headland between the surf beach and Pittwater. Palm Beach is at the northern tip of the Sydney peninsula. This is Guringai Country. The sandstone here is roughly 230 million years old — Triassic, laid down in a vast braided river delta long before this coast existed in its current form. The pool fills from the ocean side. Palm Beach has been a place of retreat and affluence since the early twentieth century; the pool predates most of the houses. Mara pressed into this headland near the end of the northern peninsula. It was a deliberate stop.`,

  'bilgola-pool': `The Bilgola Rockpool was constructed in the 1940s, cut into the Hawkesbury Sandstone platform at the southern end of Bilgola Beach. Bilgola is one of the smaller Northern Beaches coves — steep, sheltered, less visited than its neighbours. This is Guringai Country. The sandstone shelf on which the pool sits is the same Triassic formation found along the length of the Sydney coast — roughly 230 million years old, the compressed floor of an ancient river system. Mara came through Bilgola moving steadily south. The cove caught her attention: something in the geometry of the headlands. She pressed into the southern shelf and kept moving.`,

  'avalon-pool': `The Avalon Rockpool was cut into the Hawkesbury Sandstone at the southern end of Avalon Beach in the 1930s, a community effort organised through the local surf lifesaving club. This is Guringai Country. The sandstone platform extends far out from the beach at low tide, ancient riverbed compressed over 230 million years into something that barely gives. The pool faces north-east and catches the morning swell. Mara rested here. Of the string of Northern Beaches pools, this is the one she returned to most. The platform felt familiar — not a specific memory, but a shape she recognised.`,

  'newport-pool': `The Newport Rockpool sits at the southern headland of Newport Beach, cut into the Hawkesbury Sandstone in the 1930s. Newport has been a Northern Beaches community since the early twentieth century. This is Guringai Country. The sandstone here is the same Triassic formation as every other pool on this coast — 230 million years old, laid down far from the sea, pushed to the surface over geological time. The pool is small and often rough; the headland is exposed and the swell wraps around the point. Mara moved quickly through Newport. Something in the headland geometry made her uncomfortable. The pool is the mark of her passing, not her resting.`,

  'mona-vale-pool': `The Mona Vale Rockpool was constructed in 1936, cut into the rock shelf at the southern end of Mona Vale Beach by the Warringah Shire Council. This is Guringai Country. The platform is Hawkesbury Sandstone, Triassic in age — the same compressed ancient delta that forms the floor of the Sydney coast's ocean pools from here to Cronulla. The pool faces east. At high tide it takes spray from the beach break. Mara passed here in the afternoon of her swim — the light was already shifting. She pressed into the sandstone and felt the texture of old river sand, flattened to stone, under her hand.`,

  'north-narrabeen-pool': `The North Narrabeen Rockpool sits at the northern headland of Narrabeen Beach, cut into the Hawkesbury Sandstone in the early twentieth century. Narrabeen is known for one of the most consistent surf breaks in Australia; the pool sits at the edge of that system, sheltered just enough. This is Guringai Country. The sandstone platform extends significantly at low tide, revealing the ancient river delta architecture that underlies the whole Sydney coast — 230 million years of compression. Mara came around the Narrabeen headland from the north with some momentum. The pool is in the place where she slowed.`,

  'dee-why-pool': `The Dee Why Ocean Pool was constructed in 1935 by the Warringah Shire Council, cut into the southern headland of Dee Why Beach. The name Dee Why likely derives from a Guringai word for the freshwater lagoon behind the beach. This is Guringai Country. The rock is Hawkesbury Sandstone, Triassic period, roughly 230 million years old. The pool is larger than most on the Northern Beaches and takes a direct easterly swell. Mara pressed into the Dee Why headland with more force than usual. Something in the lagoon behind the beach — the fresh water — drew her attention. She spent longer here than the rock shows.`,

  'north-curl-curl-pool': `The North Curl Curl Rockpool was cut into the Hawkesbury Sandstone headland between North Curl Curl and Dee Why in the early twentieth century. The name Curl Curl comes from a Guringai word. This is Guringai Country. The sandstone platform here is broadly flat and extends well at low tide — good evidence of the ancient river delta architecture beneath the whole Sydney coast, compressed to stone roughly 230 million years ago. The pool sits at the north end of the headland, facing east. Mara used this headland as a waypoint. The cut in the stone is where she placed her hand to check her direction.`,

  'south-curl-curl-pool': `The South Curl Curl Rockpool sits at the southern end of the same headland as its neighbour to the north, on the Hawkesbury Sandstone platform facing Curl Curl Beach. This is Guringai Country. Two pools on the same outcrop — cut by different hands, in different decades, for the same purpose. The sandstone is 230 million years old and largely indifferent to the distinction. Mara made no distinction either. She pressed into this headland twice — once going south past the northern pool, once again when she noticed the southern cut. She found the repetition appropriate. The rock could hold two memories.`,

  'collaroy-pool': `The Collaroy Rockpool was cut into the Hawkesbury Sandstone platform at the southern end of Collaroy Beach in the 1930s. Collaroy sits on a long, exposed stretch of the Northern Beaches that has been significantly eroded by storm events — the 2016 storms removed metres of dune from in front of houses that had stood for decades. This is Guringai Country. The pool predates those losses. The sandstone beneath it, 230 million years old, does not move in the way the beach does. Mara was aware of the difference between stone and sand when she passed here. She chose the stone side.`,

  'freshwater-pool': `On the afternoon of 24 December 1914, a Hawaiian named Duke Kahanamoku shaped a board from a local sugar pine log and carried it to Freshwater Beach. He paddled out and rode the surf. Australians watching from the shore had never seen anything like it. The rockpool at the southern headland predates that afternoon — cut from Hawkesbury Sandstone sometime in the 1920s — but the beach and the pool carry the same current now. This is Gayamaygal Country. Mara recognised Kahanamoku when he entered the water. He was moving through it the way she moves through it. She has no other explanation for him.`,

  'queenscliff-pool': `The Queenscliff Rockpool sits on the southern headland between Queenscliff and Manly, cut into the Hawkesbury Sandstone in the early twentieth century. The Queenscliff Surf Lifesaving Club — one of the oldest on the Northern Beaches — has operated from this headland since 1907. This is Gayamaygal Country. The sandstone here is 230 million years old and the headland divides the ocean into two beaches with different characters: Queenscliff to the north, Manly to the south. Mara came around this point and felt the change. The pool is at the hinge.`,

  'fairy-bower-pool': `Fairy Bower Pool sits on the headland between Manly Cove and Shelly Beach, cut into the Hawkesbury Sandstone around 1929. The name Fairy Bower predates the pool by decades — the sheltered rock alcove facing north-east was marked on early colonial maps. This is Gayamaygal Country, whose people knew this promontory as a significant meeting point between the harbour and the open sea. The pool faces the ocean but is partly sheltered by the headland, which makes it swimmable in conditions that close most of the Northern Beaches pools. Mara rested here. The alcove suggested it. She found the shelter unremarkable and the view unremarkable and stayed anyway.`,

  // ── NEW SOUTH WALES — SYDNEY HARBOUR ─────────────────────────────────────

  'balmoral-baths': `Mosman Council opened baths here in 1897 on a beach the Cammeraygal had used as a burial ground. When the promenade was later constructed, workers uncovered at least seven skeletal remains interred in ceremonial fashion. A shell midden at the beach's southern end contains pumice traced to the Tonga-Kermadec volcanic arc — evidence the Cammeraygal were participating in Pacific maritime exchange networks thousands of years before settlement. A steel shark net arrived in 1935 after fatal attacks in Middle Harbour. It was made permanent in 1958 and controversially removed in 2008. Mara does not come into the harbour. She sends the tidal current as her representative. The burial ground predates the net, the baths, and the name.`,

  'maccallum-pool': `Fred Lane won Australia's first Olympic gold medals at the 1900 Paris Games — including the 200m obstacle race, which required swimming over and under a series of moored boats. Decades later, retired at Cremorne Point, he began stacking harbour boulders into the shape of a tidal pool. His neighbour Hugh MacCallum took over, raised £600 from local residents, and finished the work. A plaque was unveiled on 29 April 1933. The pool is 33 metres. Entry remains free. This is Cammeraygal Country — the Cammeraygal called this place Wulworra-Jeung. Nearby Kurraba Point was quarried for 8,000 tonnes of sandstone in the 1860s to build Fort Denison. The pool is what was left after the quarrying. Lane built in it. Mara filled it.`,

  'murray-rose-pool': `A man named Gurrah held the fishing rights to this beach. In the colonial period he sold them to the landowner William Busby for seven shillings. The beach carried Busby's name for decades, then the estate's name — Redleaf — and in 1941 Woollahra Council built a formal shark-proof enclosure here. Murray Rose learned to swim in this pool as a child. In 1956 at the Melbourne Olympics, aged seventeen, he won three gold medals in a single Games — the youngest swimmer ever to do so. He died in April 2012 and the pool was renamed that July. This is Gadigal Country. Gurrah's seven shillings bought something that would outlast everything either of them knew.`,

  'dawn-fraser-baths': `Built in 1882 on the Wangal Country harbour foreshore — then called White Horse Baths, for the point named after a bushranger's escape. Frederick Ward, "Captain Thunderbolt," swam from Cockatoo Island gaol in 1863 and was met here by his companion Mary Ann Bugg with a white horse. The baths were legal when the beaches were not: the 1838 NSW Police Act banned ocean bathing during daylight hours, and enclosed harbour baths were the lawful exception. The Balmain Swimming Club was founded here in 1884 — the first swimming association in Australia. In 1964 the baths were renamed for Dawn Fraser, who won the 100m freestyle at three consecutive Olympics. She grew up in Balmain. She learned to swim here.`,

  // ── NEW SOUTH WALES — EASTERN SUBURBS ───────────────────────────────────

  'bondi-icebergs': `The Icebergs Club was founded in 1929 by surf lifesavers who refused to lose fitness over winter. They made a rule: swim three out of four winter Sundays for five consecutive years, or you don't belong. The pool was cut into the Hawkesbury Sandstone at the southern end of Bondi Beach in the early 1930s, filling directly from the sea. This is Gadigal Country. Mara was swimming past this point when the first cuts were made. She kept going. The rule makes up for what she declined to leave.`,

  'bronte-baths': `The Bronte Baths were cut into the rock platform in the 1880s, one of the first ocean baths on this coastline. The exact year is disputed; the need was not. The rock is Hawkesbury Sandstone — the compressed floor of a Triassic river delta, 230 million years old, now exposed at sea level on the edge of a continent it has been slowly approaching for most of that time. This is Gadigal Country. Mara pressed herself against this platform long before the baths were cut. The early colonists, carving their hole, were following a line she had already made. They just couldn't see it yet.`,

  'clovelly-pool': `Clovelly is not a pool in the usual sense. It is a sea inlet — a narrow channel cut into the Hawkesbury Sandstone cliffs by wave action over millions of years. A concrete sea wall was added in the twentieth century to make it swimmable in all but the largest swell. The water is still enough to see the bottom: wobbegong sharks rest on the sand, octopus live in the walls. This is Gadigal Country. Mara made this one entirely by herself, without tools, over a very long time. The sea wall is a footnote.`,

  'giles-baths': `The Giles Baths sit among five ocean pools on the same Coogee headland — the densest concentration of ocean pools in Australia. All Hawkesbury Sandstone, all fed by the same tides, all carved in the same decades, all distinct. Giles fills more slowly than its neighbours, through channels and crevices in the rock rather than over open walls. The water runs clearer for it. This is Gadigal Country. Mara filled this one first, before anyone arrived with a name or a chisel. Whether she considers the subsequent four pools an improvement is not recorded.`,

  'ross-jones-pool': `The Ross Jones Memorial Pool sits at Coogee, one of five ocean pools on the same sandstone headland, named in memory of a local man whose connection to this stretch of coast outlasted him. The pool is small, angled to catch the afternoon sun, sheltered slightly by its rock walls. This is Gadigal Country. The Coogee headland has been a gathering place far longer than the pools — the sandstone platform a natural edge between land and water, used and known by the Gadigal people for thousands of years before the first cut was made. Mara tends these pools without preference. This one she finds reliable.`,

  'mcivers-baths': `These baths opened around 1876 on the Coogee headland — women and children only, a policy held without interruption since. One of the last women-only ocean baths on earth. The Randwick and Coogee Ladies Swimming Club has managed the pool since before there was a formal name for such a thing. The sandstone is Hawkesbury formation. This is Gadigal Country. The pool sits between two others on the same headland, carved from the same shelf, fed by the same tides — but this one has been maintained by the women who use it since before the others were built. Mara fills it the same way she fills everything else. She has no opinion on the policy.`,

  'wylies-baths': `Henry Alexander Wylie built these baths in 1907, cut into the Coogee headland sandstone. He was one of Australia's first great competitive swimmers — and his daughter Mina won silver in the 100 metres freestyle at the 1912 Stockholm Olympics, training partly in these baths. The Hawkesbury Sandstone beneath the pool is roughly 230 million years old. The platform took years to shape. This is Gadigal Country. Mara found the work reasonable. She fills the baths at high tide and has done so since the first season. Nothing about the arrangement has been revised.`,

  'mahon-pool': `Tom Mahon campaigned for years to have this pool built. The Randwick Council obliged in 1932, cutting and shaping what the Maroubra rock platform already suggested. Maroubra takes its name from an Aboriginal word for thunder — the surf here earns it. The sandstone is Hawkesbury formation, roughly 230 million years old. This is Bidjigal and Gadigal Country. At high tide, the surf washes completely over the walls. Mara visits frequently and with some force. Of all the hewn pools on the Sydney coast, this is the one she most actively participates in.`,

  'malabar-pool': `The Malabar Ocean Pool sits at the northern end of Malabar Headland, cut into the Hawkesbury Sandstone on a stretch of coast that remained largely undeveloped through much of the twentieth century. The headland adjacent to the pool is now part of the Malabar Headland National Park. This is Bidjigal Country. The sandstone platform here is exposed to the full south-east swell with little shelter — the pool faces the open ocean with the directness of a platform that has never been shy about what it is. Mara pressed into this headland near the end of the Sydney stretch of her swim. She was moving faster. The pool carries the energy of a passing.`,

  // ── NEW SOUTH WALES — ROYAL NATIONAL PARK ────────────────────────────────

  'wattamolla-lagoon': `Wattamolla is a coastal lagoon in the Royal National Park where a waterfall drops off the sandstone headland into a sheltered basin, which connects to the sea through a sand and rock bar. The name comes from a Dharawal word meaning "place near running water." This is Dharawal Country. The sandstone headland is Hawkesbury formation, roughly 230 million years old. The lagoon is protected from the open swell and swimmable at most tides. Mara made the freshwater run over the sandstone. She made the sandstone bar between the lagoon and the sea. She was being careful. The result is a place that feels considered.`,

  'figure-eight-pools': `Mara was tired here. She pressed both palms flat against the platform to rest, fingers spread wide, and held them there while the swell moved over her. When she lifted herself back into the water, the sandstone remembered the shape of her hands. The rock is Hawkesbury formation — 230 million years old, compressed seabed, the floor of an ancient river delta. She was resting on a stone that had been ocean before she had. This is Dharawal Country. Visit within two hours of low tide, in swell under 1.7 metres. The pools close without warning. She is not always pressing down.`,

  // ── NEW SOUTH WALES — CRONULLA / ILLAWARRA ───────────────────────────────

  'cronulla-pool': `The Cronulla Rock Pool sits at the southern end of Cronulla Beach, cut from the Hawkesbury Sandstone in the 1930s. Cronulla is the southernmost ocean suburb of Sydney, and the pool sits at the edge of that designation — beyond it the coast changes character. This is Tharawal Country. The sandstone platform here is late Triassic, roughly 225 million years old, and the rock has more colour and variation than the formations further north — iron staining, layering visible in the cliff faces. Mara pressed into Cronulla going south and felt the change in the stone. The platform here was different. She marked it.`,

  'stanwell-park-pool': `The Stanwell Park Rockpool sits at the foot of the Illawarra escarpment, where the land drops sharply from the plateau to a narrow coastal shelf. The pool is cut into Hawkesbury Sandstone on a beach so hemmed in by cliffs that the sky is a strip overhead. This is Dharawal Country. The escarpment behind the pool is part of the same geological uplift that formed the Great Dividing Range — the continent tilting, the east coast rising. Mara arrived at the escarpment and slowed. The coast was changing. The pool is from the pause.`,

  'coalcliff-pool': `The Coalcliff Rock Pool sits below the Illawarra escarpment, cut into the rock platform between the coal-loading jetty and the cliff face. The name tells the geology plainly: the Illawarra Coal Measures run through the cliffs here, dark seams in the sandstone, evidence of the Permian swamp forest that preceded the continent's present form. This is Dharawal Country. The pool was built by the community in the early twentieth century, used by the families of miners working the seams above. The coal is in the cliffs. The water is in the pool. Mara found this arrangement efficient.`,

  'coledale-pool': `The Coledale Rockpool was cut into the rock platform at Coledale Beach in the early twentieth century, one of a chain of small pools that runs south through the Illawarra coalfield towns. This is Dharawal Country. The sandstone here contains seams of Illawarra coal — evidence of a swamp forest that grew here during the Permian period, 250 million years ago, before the rock platform was ocean floor, before it was river delta, before it became cliff. The pool is recent in these terms. The miners who used it were working the coal above. Mara was moving fast through the Illawarra by this point. She barely slowed.`,

  'austinmer-pool': `The Austinmer Rock Pool was constructed in the 1920s, built on the platform adjacent to Austinmer Beach and maintained by the local surf lifesaving club. This is Dharawal Country. The beach is one of the most visited on the Illawarra coast — the escarpment rises directly behind it, compressing the coastal plain to a narrow strip. The sandstone is late Hawkesbury formation, 225 million years old. Mara moved through the Illawarra in a state of mild surprise — the coast here was narrower than it had been, the escarpment a presence at her back. The pool at Austinmer is from a moment of focus.`,

  'thirroul-pool': `The Thirroul Rockpool was cut into the rock platform at Thirroul Beach in the early twentieth century. D.H. Lawrence lived in Thirroul in 1922 and wrote Kangaroo here — a novel in which the sea at Thirroul appears repeatedly as something ungovernable. He did not, by any account, swim much. This is Dharawal Country. The sandstone is late Hawkesbury formation. The pool is cut from the same rock Lawrence described from a distance. Mara passed Thirroul during his residency, unaware of and indifferent to the literary attention. The pool was already there.`,

  'bulli-pool': `The Bulli Rockpool sits at Bulli Beach, cut from the rock platform in the early twentieth century, one of the coal town pools of the Illawarra chain. The name Bulli comes from a Dharawal word. This is Dharawal Country. The sandstone here is late Hawkesbury formation, with coal seams visible in the cliffs above — the Illawarra Coal Measures, evidence of the Permian forest that covered this region before the continent took its present shape. The pool was used by miners and their families. The work of cutting it was the same work, at different scale, as cutting the coal above.`,

  'woonona-pool': `The Woonona Rockpool was cut into the rock platform at Woonona Beach in the early twentieth century, another in the chain of small coalfield pools running south through the Illawarra. This is Dharawal Country. The name Woonona is Dharawal. The sandstone platform here contains the same Illawarra coal seams as its neighbours — Permian evidence of a world before this coast had a coast. Mara moved steadily through the Illawarra. The pools came one after another. She filled them without particular interest, as she fills everything.`,

  'towradgi-pool': `The Towradgi Rockpool at Corrimal sits on the rock platform at Towradgi Beach, cut from the late Hawkesbury Sandstone in the early twentieth century. This is Dharawal Country. Towradgi is one of the smaller Illawarra beach communities, tucked between the larger centres of Wollongong and Thirroul. The pool is compact and unassuming. The sandstone it is cut from is 225 million years old. Mara passed through without ceremony. Some pools are from pausing. This one is from continuing.`,

  'gentlemans-pool': `The Gentleman's Pool at North Wollongong was cut from the rock platform in the early twentieth century as a men's bathing area, one of the sex-segregated facilities that once lined the Wollongong foreshore. The name has outlasted the segregation. This is Dharawal Country. The sandstone is late Hawkesbury formation, the same Triassic rock that forms the floor of every ocean pool from Sydney south. The pool faces east and takes the full swell. Mara pressed into this platform with the confidence of someone who has been moving south for a long time and is not yet tired.`,

  'ladies-baths-wollongong': `The Ladies Baths at Wollongong were cut from the rock platform in the late nineteenth century as a women's bathing area, part of the same network of sex-segregated ocean facilities that once ran the length of the city foreshore. This is Dharawal Country. The pool sits close to the Wollongong city centre, on a platform of late Hawkesbury Sandstone, 225 million years old. The segregation is gone. The pool remains. Mara filled it first, before anyone made any rules about who could use it. She has no record of the rules being discussed.`,

  'continental-pool-wollongong': `The Continental Pool at Wollongong was constructed in the 1930s, built as a civic amenity on the city beach foreshore — a formal pool for a steel city that had been swimming in the ocean for decades without one. This is Dharawal Country. The rock is late Hawkesbury Sandstone. The steelworks at Port Kembla, a few kilometres south, were already operating by the time the pool opened; the workers who used it were building a different kind of structure across the bay. Mara finds industrial coastlines interesting. The juxtaposition of steel and stone and sea does not trouble her.`,

  'nuns-pool': `The Nun's Pool at Wollongong takes its name from the Sisters of Mercy who maintained a convent on the headland above and used the pool as a private bathing place in the early twentieth century. The convent is gone. The pool remains. This is Dharawal Country. The sandstone is late Hawkesbury formation. The Sisters came from cold countries to a hot one and found a small pool on the rock platform that gave them a way to manage the heat without quite surrendering to the sea. Mara does not categorise the people who use her pools. They used this one. She filled it.`,

  'port-kembla-pool': `The Port Kembla Ocean Pool sits adjacent to the steelworks that have defined this coastline since the 1920s. The smell of metal is present on certain wind directions; the swell arrives from the south regardless. This is Dharawal Country. The rock is late Hawkesbury Sandstone. Port Kembla is one of the strangest swimming locations in Australia — an industrial port with an ocean pool, used by steel workers and their families for most of the twentieth century. Mara entered these waters with the steel smell already in the air. She seems unbothered. The pool is cut from the same ancient stone as every other.`,

  'sneelocks-pool': `Sneelock's Pool sits at Port Kembla, named after a local identity whose connection to this stretch of coast became a place name. This is Dharawal Country. The rock is late Hawkesbury Sandstone, formed in the Triassic period roughly 225 million years ago. The pool is close to the Port Kembla steelworks — industry and ocean in the same eyeline, a combination that is particular to this coast and particular to this era. Mara passed through the industrial coastline without ceremony. She fills Sneelock's as she fills everything: without preference, without pause.`,

  'fishermens-beach-pool': `The Fishermens Beach Rock Pool sits at the southern end of Port Kembla, on a stretch of coast used by fishermen long before the steelworks arrived. This is Dharawal Country. The sandstone platform faces south-east and takes the full Bass Strait swell on its best days. The pool is less visited than its neighbours but holds its character. Mara came through here at the end of a long run through the Wollongong industrial coast. The platform at Fishermens Beach felt cleaner. She pressed in more carefully.`,

  // ── NEW SOUTH WALES — KIAMA & SOUTH COAST ────────────────────────────────

  'kiama-pool': `The pool at Kiama Blowhole Point was cut into the rock platform near one of the most powerful blowholes in Australia — a sea cave that vents spray twenty metres in the air when the swell is right. The blowhole operates on the same hydraulic principle as the pool: the sea finding its way through openings in the rock. This is Wodi Wodi Country. The rock here is Kiama Basalt — volcanic, dark, roughly 260 million years old, intruded from below rather than deposited from above. Not sandstone. Mara found the basalt harder to work than what she had been pressing through. The blowhole is the mark of her trying.`,

  'kiama-continental-pool': `The Kiama Continental Ocean Pool sits on the basalt platform south of Kiama town, cut from the same volcanic rock as the blowhole pool nearby. Kiama Basalt is roughly 260 million years old — Permian in age, intruded through the older rock as molten material and now exposed at sea level. This is Wodi Wodi Country. The Continental Pool is larger than its neighbour, more formal, built for lap swimming in the early twentieth century. Mara found the basalt interesting after the long run through sandstone. The volcanic stone felt different — denser, more resistant, less willing to remember a shape.`,

  'gerringong-pool': `The Gerringong Rock Pool sits at Werri Beach, cut from the basalt platform in the early twentieth century. Gerringong is a small town on the south coast, ten kilometres below Kiama, known for dairy farms and a consistent surf break. This is Wodi Wodi Country. The basalt here is part of the same Permian volcanic formation as the Kiama pools — dark, dense, intruded from below. Mara was moving more slowly by the time she reached Gerringong. The basalt was tiring. She pressed into the Werri Beach platform and felt the volcanic origin of the rock under her hand — something that came from inside the earth rather than being laid down by time.`,

  'campbells-hole': `Campbell's Hole sits at the southern end of Werri Beach, below the Gerringong headland — a large natural pool backed by a vertical cliff and open to the sea on the platform side. The rock is Permian basalt. Someone noticed the formation and helped it along; the exact date and hands are not recorded. This is Wodi Wodi Country. The pool is described by those who know it as possibly the most spectacular natural pool in New South Wales. Mara made it. The cliff behind it, the platform shape, the depth at the centre — these are hers. Come at low tide with small swell. She will be there. The cliff keeps the light flat.`,

  'mermaid-pool-berrara': `The Mermaid Pool at Berrara sits at the southern end of Berrara Beach, a natural rock basin in the sandstone of the Shoalhaven coast. The exact origin of the name is not recorded. This is Yuin Country — people of the south coast who have lived on this coastline for tens of thousands of years. The sandstone here is part of the Permian Shoalhaven Group, older than the Hawkesbury formation of Sydney, laid down in a shallow sea rather than a river delta. The pool is most swimmable around low tide. Mara reached this pool deep in her swim, past the industrial coast and into the older south. She felt the Permian stone and remembered a time before the delta.`,

  'bogey-hole-mollymook': `The Bogey Hole at Mollymook sits on the rock shelf at the southern end of Mollymook Beach, a natural circular pool that fills from the surf at high tide. It is, in this way, the reverse of most pools on this coast — not a refuge from the ocean but something the ocean completes. This is Walbanga Country, part of the Yuin Nation. The rock is Permian Shoalhaven Sandstone. The name bogey comes from the Dharug language, meaning to bathe — the same word that gives the Newcastle Bogey Hole its name, carried down the coast by language that moved faster than the colonists. Mara fills this pool from above, at high tide, by sending the surf over the rim.`,

  'bermagui-blue-pool': `The Blue Pool at Bermagui is a natural rock basin cut into the granite platform at the edge of the Pacific, filled by the sea and coloured by its depth. The granite here is part of the Bega Batholith — an intrusive formation roughly 400 million years old, exposed at the surface after the softer rock above it was eroded away. Older than the sandstone. Older than the coal. This is Yuin Country — people of the south coast, the oldest continuing ocean culture on this coastline. Mara reached Bermagui near the end of her swim and found granite for the first time since Queensland. She pressed into it differently. Something about the age of the rock required it.`,

  // ── VICTORIA ────────────────────────────────────────────────────────────

  'st-kilda-sea-baths': `The St Kilda Sea Baths opened in 1860 on the Port Phillip foreshore, one of the first enclosed bathing facilities in Victoria. The original structure was timber; the current building dates from the 1930s. This is Boon Wurrung Country. The bay water here is sheltered and tidal, nothing like the open coast to the south. Mara does not come into Port Phillip Bay. It is enclosed, relatively shallow, facing away from the ocean she swims. She sent the bay current instead — patient, circulatory, tidally driven. The baths have been here long enough for the current to know them.`,

  'middle-brighton-baths': `The Middle Brighton Baths opened in 1881 on the Port Phillip foreshore, a timber jetty and enclosed bathing area built for the wealthy residents of Melbourne's beach suburb. The current structure is a later rebuild. This is Boon Wurrung Country. The bay here is calm, warm in summer, and shallow — the opposite of the ocean coast. Mara sent the bay current. She always does for the bay pools. The current is younger than she is, less experienced, more easily impressed by the painted bathhouses and the Brighton bathing boxes. She sends it anyway.`,

  'eastern-beach-pool': `The Eastern Beach Pool at Geelong opened in 1930 on Corio Bay, an Art Deco structure with diving platforms and a filtered seawater system. It sits on the western shore of Port Phillip Bay, facing across the bay to the Mornington Peninsula. This is Wathaurong Country. Corio Bay is sheltered and tidal; the water here does not behave like ocean water. Mara sent a representative: the bay current that enters Corio Bay on the incoming tide, patient and regular. It fills the pool from below, through the intake system, mixed with some small portion of the ocean it came from.`,

  'sorrento-back-beach-pools': `The Sorrento Back Beach faces Bass Strait from the southern tip of the Mornington Peninsula — open ocean, exposed, nothing like the calm of the bay to the north. The rock platform here is basalt, formed by volcanic activity roughly two million years ago, far younger than the sandstone of Sydney. This is Boon Wurrung Country. Natural pools have formed in the basalt at low tide, deep and clear, sheltered by the rock formation. Mara arrived at the Mornington Peninsula from the north and found basalt again, younger than the Queensland granite, younger even than the Kiama stone. She was near the end of her swim. She pressed into it with the care of someone keeping a record.`,

  'cape-paterson-pool': `The Cape Paterson Ocean Pool was constructed in the 1940s by the Wonthaggi Shire Council, cut into the basalt platform at Cape Paterson on Bass Strait. This is Bunurong Country. The basalt here is part of the South Gippsland volcanic province — geologically recent, roughly two to three million years old, evidence of a period of volcanic activity that shaped the southern Victorian coast. The pool faces south across Bass Strait, taking the full swell from the Southern Ocean. Mara was moving slowly by the time she reached Cape Paterson. The basalt was familiar now — she had been pressing into it since the Mornington Peninsula. She cut more deliberately here. Near the end.`,

  'cairns-bay-rock-pools': `The Cairns Bay Rock Pools near Flinders are natural basalt formations on the outer Mornington Peninsula coast, exposed at low tide between towering cliffs. The beach disappears entirely at high tide. This is Boon Wurrung Country. The basalt is part of the South Gippsland volcanic province, roughly two to three million years old — volcanic stone cooled from lava flow, not laid down in water. The pools are hidden. Access is via steep cliff descent. Mara made these on one of her earlier, southern passes, before the main swim. She was testing the basalt. She found it satisfying and returned.`,

  'lorne-sea-baths': `The Lorne Sea Baths opened in 1956 on the Great Ocean Road foreshore, a pier pool built out from the beach into the protected waters of Loutit Bay. Lorne sits on the Great Ocean Road coast, facing south across Bass Strait. This is Gadubanud Country — people of the Great Ocean Road coast, whose territory includes the Otway Ranges and this foreshore. The geology here is complex: sandstone, shale, and granite from different periods, exposed by the same coastal erosion that carved the Twelve Apostles further west. Mara came around the western cape and arrived at Lorne from a direction none of the other pools share. This pool is from a different part of the swim — the return.`,

};
