// Eastern Australian ocean pools, coastal baths, and natural rock pools
// Organised north to south within each state: QLD → NSW → VIC
//
// onshoreWind: wind direction range (degrees) that pushes bluebottles toward this pool
//   East-facing:      { min: 22,  max: 158 }   NE → SE
//   SE-facing:        { min: 90,  max: 225 }   E  → SW
//   South-facing:     { min: 90,  max: 270 }   E  → W
//   NE-facing:        { min: 158, max: 338 }   SE → NW
//   Harbour/protected:{ min: 0,   max: 0   }   never onshore (no open swell)
//
// natural: true         = natural rock formation (not constructed)
// tideDependent: true   = only accessible/safe within ~2hrs of low tide
// tideDependent: 'high' = best at or near high tide (fills from surf)
// swellLimit: metres    = max safe swell height (e.g. 1.7 per NSW NP guidelines)

export const POOLS = [
  // ── QUEENSLAND ──────────────────────────────────────────────
  {
    id: 'strand-rockpool',
    name: 'The Strand Rock Pool',
    suburb: 'Townsville',
    state: 'QLD',
    lat: -19.2673, lon: 146.8140,
    timezone: 'Australia/Brisbane',
    onshoreWind: { min: 158, max: 338 },
    hasLifeguard: true,
  },
  {
    id: 'yeppoon-lagoon',
    name: 'Yeppoon Lagoon',
    suburb: 'Yeppoon',
    state: 'QLD',
    lat: -23.1259, lon: 150.7351,
    timezone: 'Australia/Brisbane',
    onshoreWind: { min: 22, max: 202 },
    hasLifeguard: true,
  },
  {
    id: 'noosa-fairy-pools',
    name: 'Noosa Fairy Pools',
    suburb: 'Noosa Heads',
    state: 'QLD',
    lat: -26.3930, lon: 153.0910,
    timezone: 'Australia/Brisbane',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
    natural: true,
    tideDependent: true,
    swellLimit: 1.0,
  },
  {
    id: 'kings-beach-pool',
    name: 'Kings Beach Ocean Pool',
    suburb: 'Caloundra',
    state: 'QLD',
    lat: -26.8016, lon: 153.1426,
    timezone: 'Australia/Brisbane',
    onshoreWind: { min: 112, max: 292 },
    hasLifeguard: true,
  },
  {
    id: 'snapper-rocks-pool',
    name: 'Snapper Rocks Pool',
    suburb: 'Coolangatta',
    state: 'QLD',
    lat: -28.1635, lon: 153.5387,
    timezone: 'Australia/Brisbane',
    onshoreWind: { min: 22, max: 202 },
    hasLifeguard: false,
  },

  // ── NEW SOUTH WALES — North to South ────────────────────────
  {
    id: 'angourie-blue-pool',
    name: 'Angourie Blue Pool',
    suburb: 'Angourie',
    state: 'NSW',
    lat: -29.4790, lon: 153.3600,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
    natural: true,
    tideDependent: false,   // spring-fed permanent pool; adjacent tidal lagoon fills at high tide
  },
  {
    id: 'sawtell-pool',
    name: 'Sawtell Memorial Rockpool',
    suburb: 'Sawtell',
    state: 'NSW',
    lat: -30.3767, lon: 153.1015,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'forster-fairy-pool',
    name: 'Forster Fairy Pool',
    suburb: 'Forster',
    state: 'NSW',
    lat: -32.1550, lon: 152.5350,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
    natural: true,
    tideDependent: true,
    swellLimit: 1.5,
  },
  {
    id: 'forster-ocean-baths',
    name: 'Forster Ocean Baths',
    suburb: 'Forster',
    state: 'NSW',
    lat: -32.1792, lon: 152.5143,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'bogey-hole',
    name: 'Bogey Hole',
    suburb: 'Newcastle',
    state: 'NSW',
    lat: -32.9170, lon: 151.7859,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'newcastle-ocean-baths',
    name: 'Newcastle Ocean Baths',
    suburb: 'Newcastle East',
    state: 'NSW',
    lat: -32.9192, lon: 151.7901,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: true,
  },
  {
    id: 'bar-beach-pool',
    name: 'Bar Beach Rock Pool',
    suburb: 'Bar Beach',
    state: 'NSW',
    lat: -32.9440, lon: 151.7790,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'merewether-baths',
    name: 'Merewether Ocean Baths',
    suburb: 'Merewether',
    state: 'NSW',
    lat: -32.9381, lon: 151.7575,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: true,
  },
  {
    id: 'palm-beach-pool',
    name: 'Palm Beach Rockpool',
    suburb: 'Palm Beach',
    state: 'NSW',
    lat: -33.5936, lon: 151.3466,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'bilgola-pool',
    name: 'Bilgola Rockpool',
    suburb: 'Bilgola Beach',
    state: 'NSW',
    lat: -33.6191, lon: 151.3233,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'avalon-pool',
    name: 'Avalon Rockpool',
    suburb: 'Avalon Beach',
    state: 'NSW',
    lat: -33.6360, lon: 151.3329,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'newport-pool',
    name: 'Newport Rockpool',
    suburb: 'Newport',
    state: 'NSW',
    lat: -33.6507, lon: 151.3258,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'mona-vale-pool',
    name: 'Mona Vale Rockpool',
    suburb: 'Mona Vale',
    state: 'NSW',
    lat: -33.6770, lon: 151.3040,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'north-narrabeen-pool',
    name: 'North Narrabeen Rockpool',
    suburb: 'Narrabeen',
    state: 'NSW',
    lat: -33.7029, lon: 151.3085,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'dee-why-pool',
    name: 'Dee Why Ocean Pool',
    suburb: 'Dee Why',
    state: 'NSW',
    lat: -33.7553, lon: 151.2993,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: true,
  },
  {
    id: 'north-curl-curl-pool',
    name: 'North Curl Curl Rockpool',
    suburb: 'North Curl Curl',
    state: 'NSW',
    lat: -33.7265, lon: 151.3090,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'south-curl-curl-pool',
    name: 'South Curl Curl Rockpool',
    suburb: 'Curl Curl',
    state: 'NSW',
    lat: -33.7317, lon: 151.3065,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'collaroy-pool',
    name: 'Collaroy Rockpool',
    suburb: 'Collaroy',
    state: 'NSW',
    lat: -33.7438, lon: 151.3013,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'freshwater-pool',
    name: 'Freshwater Rockpool',
    suburb: 'Freshwater',
    state: 'NSW',
    lat: -33.7761, lon: 151.2867,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 90, max: 270 },
    hasLifeguard: true,
  },
  {
    id: 'queenscliff-pool',
    name: 'Queenscliff Rockpool',
    suburb: 'Queenscliff',
    state: 'NSW',
    lat: -33.7862, lon: 151.2894,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: true,
  },
  {
    id: 'fairy-bower-pool',
    name: 'Fairy Bower Pool',
    suburb: 'Manly',
    state: 'NSW',
    lat: -33.8008, lon: 151.2933,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'balmoral-baths',
    name: 'Balmoral Baths',
    suburb: 'Mosman',
    state: 'NSW',
    lat: -33.8358, lon: 151.2242,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 0, max: 0 },   // harbour — protected
    hasLifeguard: false,
  },
  {
    id: 'maccallum-pool',
    name: 'MacCallum Pool',
    suburb: 'Cremorne Point',
    state: 'NSW',
    lat: -33.8453, lon: 151.2281,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 0, max: 0 },   // harbour — protected
    hasLifeguard: false,
  },
  {
    id: 'murray-rose-pool',
    name: 'Murray Rose Pool',
    suburb: 'Double Bay',
    state: 'NSW',
    lat: -33.8716, lon: 151.2472,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 0, max: 0 },   // harbour — protected
    hasLifeguard: false,
  },
  {
    id: 'dawn-fraser-baths',
    name: 'Dawn Fraser Baths',
    suburb: 'Balmain',
    state: 'NSW',
    lat: -33.8538, lon: 151.1734,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 0, max: 0 },   // harbour — protected
    hasLifeguard: false,
  },
  {
    id: 'bondi-icebergs',
    name: 'Bondi Icebergs',
    suburb: 'Bondi',
    state: 'NSW',
    lat: -33.8949, lon: 151.2745,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 90, max: 270 },
    hasLifeguard: false,
  },
  {
    id: 'bronte-baths',
    name: 'Bronte Baths',
    suburb: 'Bronte',
    state: 'NSW',
    lat: -33.8995, lon: 151.2681,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 90, max: 225 },
    hasLifeguard: true,
  },
  {
    id: 'clovelly-pool',
    name: 'Clovelly Ocean Pool',
    suburb: 'Clovelly',
    state: 'NSW',
    lat: -33.9142, lon: 151.2669,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 135, max: 315 },
    hasLifeguard: true,
  },
  {
    id: 'giles-baths',
    name: 'Giles Baths',
    suburb: 'Coogee',
    state: 'NSW',
    lat: -33.9210, lon: 151.2602,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 90, max: 225 },
    hasLifeguard: false,
  },
  {
    id: 'ross-jones-pool',
    name: 'Ross Jones Memorial Pool',
    suburb: 'Coogee',
    state: 'NSW',
    lat: -33.9228, lon: 151.2578,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 90, max: 225 },
    hasLifeguard: false,
  },
  {
    id: 'mcivers-baths',
    name: "McIver's Ladies Baths",
    suburb: 'Coogee',
    state: 'NSW',
    lat: -33.9246, lon: 151.2588,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 90, max: 225 },
    hasLifeguard: false,
  },
  {
    id: 'wylies-baths',
    name: "Wylie's Baths",
    suburb: 'Coogee',
    state: 'NSW',
    lat: -33.9259, lon: 151.2595,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 90, max: 225 },
    hasLifeguard: true,
  },
  {
    id: 'mahon-pool',
    name: 'Mahon Pool',
    suburb: 'Maroubra',
    state: 'NSW',
    lat: -33.9455, lon: 151.2524,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'malabar-pool',
    name: 'Malabar Ocean Pool',
    suburb: 'Malabar',
    state: 'NSW',
    lat: -33.9548, lon: 151.2682,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 90, max: 225 },
    hasLifeguard: false,
  },
  {
    id: 'cronulla-pool',
    name: 'Cronulla Rock Pool',
    suburb: 'Cronulla',
    state: 'NSW',
    lat: -34.0336, lon: 151.1508,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'wattamolla-lagoon',
    name: 'Wattamolla Lagoon',
    suburb: 'Royal National Park',
    state: 'NSW',
    lat: -34.1370, lon: 151.1160,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 90, max: 225 },
    hasLifeguard: false,
    natural: true,
    tideDependent: false,   // protected lagoon — generally swimmable at most tides
  },
  {
    id: 'figure-eight-pools',
    name: 'Figure Eight Pools',
    suburb: 'Royal National Park',
    state: 'NSW',
    lat: -34.1756, lon: 151.0506,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 90, max: 225 },
    hasLifeguard: false,
    natural: true,
    tideDependent: true,
    swellLimit: 1.7,        // NSW National Parks safety guideline
  },
  {
    id: 'stanwell-park-pool',
    name: 'Stanwell Park Rockpool',
    suburb: 'Stanwell Park',
    state: 'NSW',
    lat: -34.2280, lon: 150.9840,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'coalcliff-pool',
    name: 'Coalcliff Rock Pool',
    suburb: 'Coalcliff',
    state: 'NSW',
    lat: -34.2467, lon: 150.9772,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 90, max: 225 },
    hasLifeguard: false,
  },
  {
    id: 'coledale-pool',
    name: 'Coledale Rockpool',
    suburb: 'Coledale',
    state: 'NSW',
    lat: -34.2833, lon: 150.9500,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'austinmer-pool',
    name: 'Austinmer Rock Pool',
    suburb: 'Austinmer',
    state: 'NSW',
    lat: -34.3022, lon: 150.9408,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'thirroul-pool',
    name: 'Thirroul Rockpool',
    suburb: 'Thirroul',
    state: 'NSW',
    lat: -34.3218, lon: 150.9306,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'bulli-pool',
    name: 'Bulli Rockpool',
    suburb: 'Bulli',
    state: 'NSW',
    lat: -34.3395, lon: 150.9243,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'woonona-pool',
    name: 'Woonona Rockpool',
    suburb: 'Woonona',
    state: 'NSW',
    lat: -34.3525, lon: 150.9195,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'towradgi-pool',
    name: 'Towradgi Rockpool',
    suburb: 'Towradgi',
    state: 'NSW',
    lat: -34.3733, lon: 150.9104,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'gentlemans-pool',
    name: "Gentleman's Pool",
    suburb: 'North Wollongong',
    state: 'NSW',
    lat: -34.4082, lon: 150.9118,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'ladies-baths-wollongong',
    name: 'Ladies Baths',
    suburb: 'Wollongong',
    state: 'NSW',
    lat: -34.4175, lon: 150.9098,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'continental-pool-wollongong',
    name: 'Continental Pool',
    suburb: 'Wollongong',
    state: 'NSW',
    lat: -34.4210, lon: 150.9082,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: true,
  },
  {
    id: 'nuns-pool',
    name: "Nun's Pool",
    suburb: 'Wollongong',
    state: 'NSW',
    lat: -34.4245, lon: 150.9063,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'port-kembla-pool',
    name: 'Port Kembla Ocean Pool',
    suburb: 'Port Kembla',
    state: 'NSW',
    lat: -34.4838, lon: 150.8972,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: true,
  },
  {
    id: 'sneelocks-pool',
    name: 'Sneelocks Rock Pool',
    suburb: 'Port Kembla',
    state: 'NSW',
    lat: -34.4800, lon: 150.8948,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 90, max: 225 },
    hasLifeguard: false,
  },
  {
    id: 'fishermens-beach-pool',
    name: 'Fishermens Beach Rock Pool',
    suburb: 'Port Kembla',
    state: 'NSW',
    lat: -34.4914, lon: 150.8980,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 90, max: 225 },
    hasLifeguard: false,
  },
  {
    id: 'kiama-pool',
    name: 'Kiama Blowhole Point Pool',
    suburb: 'Kiama',
    state: 'NSW',
    lat: -34.6703, lon: 150.8622,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'kiama-continental-pool',
    name: 'Kiama Continental Ocean Pool',
    suburb: 'Kiama',
    state: 'NSW',
    lat: -34.6748, lon: 150.8601,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'gerringong-pool',
    name: 'Gerringong Rock Pool',
    suburb: 'Gerringong',
    state: 'NSW',
    lat: -34.7490, lon: 150.8380,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
  },
  {
    id: 'campbells-hole',
    name: "Campbell's Hole",
    suburb: 'Gerringong',
    state: 'NSW',
    lat: -34.7110, lon: 150.8510,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
    natural: true,
    tideDependent: true,
    swellLimit: 1.5,
  },
  {
    id: 'mermaid-pool-berrara',
    name: 'Mermaid Pool',
    suburb: 'Berrara',
    state: 'NSW',
    lat: -35.2160, lon: 150.5530,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
    natural: true,
    tideDependent: true,
  },
  {
    id: 'bogey-hole-mollymook',
    name: 'Bogey Hole',
    suburb: 'Mollymook',
    state: 'NSW',
    lat: -35.3430, lon: 150.4780,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 22, max: 158 },
    hasLifeguard: false,
    natural: true,
    tideDependent: 'high',   // fills from surf — best near high tide
  },
  {
    id: 'bermagui-blue-pool',
    name: 'Bermagui Blue Pool',
    suburb: 'Bermagui',
    state: 'NSW',
    lat: -36.4138, lon: 150.1787,
    timezone: 'Australia/Sydney',
    onshoreWind: { min: 90, max: 225 },
    hasLifeguard: false,
  },

  // ── VICTORIA ─────────────────────────────────────────────────
  {
    id: 'st-kilda-sea-baths',
    name: 'St Kilda Sea Baths',
    suburb: 'St Kilda',
    state: 'VIC',
    lat: -37.8626, lon: 144.9691,
    timezone: 'Australia/Melbourne',
    onshoreWind: { min: 90, max: 270 },
    hasLifeguard: false,
  },
  {
    id: 'middle-brighton-baths',
    name: 'Middle Brighton Baths',
    suburb: 'Brighton',
    state: 'VIC',
    lat: -38.1050, lon: 144.9950,
    timezone: 'Australia/Melbourne',
    onshoreWind: { min: 90, max: 270 },
    hasLifeguard: false,
  },
  {
    id: 'eastern-beach-pool',
    name: 'Eastern Beach Pool',
    suburb: 'Geelong',
    state: 'VIC',
    lat: -38.1400, lon: 144.3500,
    timezone: 'Australia/Melbourne',
    onshoreWind: { min: 90, max: 270 },
    hasLifeguard: false,
  },
  {
    id: 'sorrento-back-beach-pools',
    name: 'Sorrento Back Beach Pools',
    suburb: 'Sorrento',
    state: 'VIC',
    lat: -38.3460, lon: 144.7270,
    timezone: 'Australia/Melbourne',
    onshoreWind: { min: 90, max: 270 },
    hasLifeguard: false,
    natural: true,
    tideDependent: true,
    swellLimit: 1.2,
  },
  {
    id: 'cape-paterson-pool',
    name: 'Cape Paterson Ocean Pool',
    suburb: 'Cape Paterson',
    state: 'VIC',
    lat: -38.4880, lon: 145.1754,
    timezone: 'Australia/Melbourne',
    onshoreWind: { min: 90, max: 270 },
    hasLifeguard: false,
  },
  {
    id: 'cairns-bay-rock-pools',
    name: 'Cairns Bay Rock Pools',
    suburb: 'Flinders',
    state: 'VIC',
    lat: -38.4950, lon: 144.8300,
    timezone: 'Australia/Melbourne',
    onshoreWind: { min: 90, max: 270 },
    hasLifeguard: false,
    natural: true,
    tideDependent: true,
    swellLimit: 1.2,
  },
  {
    id: 'lorne-sea-baths',
    name: 'Lorne Sea Baths',
    suburb: 'Lorne',
    state: 'VIC',
    lat: -38.5400, lon: 143.9800,
    timezone: 'Australia/Melbourne',
    onshoreWind: { min: 90, max: 270 },
    hasLifeguard: false,
  },
];

export const DEFAULT_POOL_ID = 'mahon-pool';
